// Regenerate egg-flix.json from install.sh + the definitions below.
// The egg format (PTDL_v2) wants the whole install script flattened into one
// JSON string — unmaintainable by hand, so install.sh stays the readable
// source of truth and this script assembles the export:
//
//   node deploy/pterodactyl/build-egg.mjs
//
// Import the resulting egg-flix.json in the panel: Admin → Nests → Import Egg.

import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

const here = path.dirname(new URL(import.meta.url).pathname);
const script = readFileSync(path.join(here, "install.sh"), "utf8");

function variable(name, description, envVariable, defaultValue, rules, extra = {}) {
  return {
    name,
    description,
    env_variable: envVariable,
    default_value: defaultValue,
    user_viewable: true,
    user_editable: true,
    rules,
    field_type: "text",
    ...extra,
  };
}

const egg = {
  _comment: "DO NOT EDIT: FILE GENERATED BY deploy/pterodactyl/build-egg.mjs — edit install.sh / build-egg.mjs and regenerate.",
  meta: { version: "PTDL_v2", update_url: null },
  exported_at: "2026-07-03T12:00:00+00:00",
  name: "Flix",
  author: "bayabenyedderpro@gmail.com",
  description:
    "Flix — self-hosted, 100% offline video platform (Netflix-style UI, direct-play/remux/transcode adaptive playback, local recommendations, watch-together). " +
    "Upload your library to /home/container/media, start, and open the allocation port in a browser.",
  features: null,
  docker_images: {
    "Node 22": "ghcr.io/parkervcp/yolks:nodejs_22",
  },
  file_denylist: [],
  startup: "node /home/container/start.mjs",
  config: {
    files: "{}",
    startup: JSON.stringify({ done: "[flix] ready" }, null, 4),
    logs: "{}",
    stop: "^C",
  },
  scripts: {
    installation: {
      script,
      container: "node:22-bookworm-slim",
      entrypoint: "bash",
    },
  },
  variables: [
    variable(
      "Version",
      "Release Flix à installer (tag de release GitHub, ex. v0.2.0) ou 'latest'. Utilisé uniquement à l'installation/réinstallation.",
      "FLIX_VERSION",
      "latest",
      "required|string|max:32",
    ),
    variable(
      "Dépôt GitHub",
      "Dépôt owner/repo d'où télécharger le bundle serveur (ou construire depuis les sources si aucun asset de release n'existe).",
      "GITHUB_REPO",
      "ybenyedder/flix",
      "required|string|max:191",
    ),
    variable(
      "Dossier médiathèque",
      "Dossier scanné et diffusé. Déposez-y vos films/séries via SFTP.",
      "FLIX_MEDIA_DIR",
      "/home/container/media",
      "required|string|max:191",
    ),
    variable(
      "Dossier données",
      "Base SQLite, cache d'images et scratch de transcodage. Laissez la valeur par défaut sauf besoin précis.",
      "FLIX_DATA_DIR",
      "/home/container/data",
      "required|string|max:191",
    ),
    variable(
      "Chemin ffmpeg",
      "Binaire ffmpeg statique installé par le script d'installation.",
      "FFMPEG_PATH",
      "/home/container/ffmpeg/ffmpeg",
      "required|string|max:191",
    ),
    variable(
      "Chemin ffprobe",
      "Binaire ffprobe statique installé par le script d'installation.",
      "FFPROBE_PATH",
      "/home/container/ffmpeg/ffprobe",
      "required|string|max:191",
    ),
    variable(
      "Mot de passe admin initial",
      "Optionnel. S'il est vide, un mot de passe temporaire est généré au premier démarrage et affiché dans la console.",
      "FLIX_ADMIN_PASSWORD",
      "",
      "nullable|string|max:191",
    ),
    variable(
      "Transcodages simultanés max",
      "Nombre maximum de sessions ffmpeg remux/transcodage simultanées. Montez-le seulement si le CPU suit.",
      "FLIX_MAX_TRANSCODES",
      "2",
      "required|integer|between:1,16",
    ),
    variable(
      "Hauteur max de transcodage",
      "Garde-fou CPU : résolution verticale maximale d'un transcodage logiciel (le direct play/remux n'est jamais limité).",
      "FLIX_MAX_TRANSCODE_HEIGHT",
      "1080",
      "required|integer|between:360,2160",
    ),
    variable(
      "Trickplay (aperçus de scrubbing)",
      "1 = générer les vignettes de prévisualisation de la barre de lecture (coût ffmpeg par fichier au scan).",
      "FLIX_TRICKPLAY",
      "0",
      "required|boolean",
    ),
    variable(
      "Format des logs",
      "pretty = lignes lisibles dans cette console ; json = logs structurés.",
      "FLIX_LOG_FORMAT",
      "pretty",
      "required|string|in:pretty,json",
    ),
  ],
};

const out = path.join(here, "egg-flix.json");
writeFileSync(out, JSON.stringify(egg, null, 4) + "\n");
console.log(`[build-egg] wrote ${out}`);
